/*
 * Copyright (C) 2026 Eric Molitor <github.com/emolitor>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PIO-based SWD driver for RP2040/RP2350.
 *
 * PIO program and inline helpers for configuring and driving SWD via a
 * PIO state machine.  Uses the ChibiOS PIO LLD (PIOv1) for state machine
 * allocation, program loading, and register access.
 *
 * PIO assembly source is in probe_swd.pio; the instruction array is
 * generated by pioasm into probe_swd.pio.h.
 *
 * The PIO program implements a command-dispatch architecture:
 *   - Command word: bits[7:0]=count-1, bit[8]=direction, bits[13:9]=PC
 *   - Side-set: 1-bit optional on SWCLK (4 PIO cycles per SWCLK edge)
 *   - Writes are fire-and-forget (TX FIFO only)
 *   - Reads block on RX FIFO
 */

#ifndef PIO_SWD_H
#define PIO_SWD_H

#include "hal.h"
#include "rp_pio.h"

/*===========================================================================*/
/* PIO program: generated by pioasm from probe_swd.pio.                      */
/*===========================================================================*/

/* Skip Pico SDK struct/helpers — we only need the instruction array. */
#define PICO_NO_HARDWARE 1
#include "probe_swd.pio.h"
#undef PICO_NO_HARDWARE

/* Map generated names to local constants. */
#define PIO_SWD_OFFSET_WRITE_CMD      probe_swd_offset_write_cmd
#define PIO_SWD_OFFSET_TURNAROUND_CMD probe_swd_offset_turnaround_cmd
#define PIO_SWD_OFFSET_GET_NEXT_CMD   probe_swd_offset_get_next_cmd
#define PIO_SWD_OFFSET_READ_CMD       probe_swd_offset_read_cmd
#define PIO_SWD_WRAP_TARGET           probe_swd_wrap_target
#define PIO_SWD_WRAP                  probe_swd_wrap
#define PIO_SWD_PROGRAM_LEN           (sizeof(probe_swd_program_instructions) / sizeof(uint16_t))

/*===========================================================================*/
/* PIO program descriptor for LLD.                                           */
/*===========================================================================*/

static const rp_pio_program_t pio_swd_program = {
  .instructions = probe_swd_program_instructions,
  .length       = sizeof(probe_swd_program_instructions) / sizeof(uint16_t),
  .origin       = 0   /* Load at offset 0. */
};

/*===========================================================================*/
/* Command word construction.                                                */
/*===========================================================================*/

/* Command types — resolved to PIO instruction addresses. */
#define PIO_SWD_CMD_WRITE       PIO_SWD_OFFSET_WRITE_CMD
#define PIO_SWD_CMD_READ        PIO_SWD_OFFSET_READ_CMD
#define PIO_SWD_CMD_TURNAROUND  PIO_SWD_OFFSET_TURNAROUND_CMD
#define PIO_SWD_CMD_SKIP        PIO_SWD_OFFSET_GET_NEXT_CMD

/**
 * @brief   Build a PIO SWD command word.
 *
 * @param[in] bit_count   number of bits (1..256)
 * @param[in] out_en      true=output, false=input
 * @param[in] cmd_offset  command label offset within program
 * @param[in] prog_offset base address of program in PIO instruction memory
 * @return    32-bit command word for TX FIFO
 */
static inline uint32_t pio_swd_cmd(uint32_t bit_count, bool out_en,
                                    uint32_t cmd_offset,
                                    uint32_t prog_offset) {
  uint32_t addr = prog_offset + cmd_offset;
  return ((bit_count - 1U) & 0xFFU) |
         ((uint32_t)out_en << 8) |
         (addr << 9);
}

/*===========================================================================*/
/* PIO state machine configuration.                                          */
/*===========================================================================*/

/**
 * @brief   Configure state machine for SWD operation.
 * @pre     SM must be allocated via pioSmAlloc() and program loaded via
 *          pioProgramLoad().
 *
 * @param[in] smp          allocated state machine descriptor
 * @param[in] prog_offset  program offset from pioProgramLoad()
 * @param[in] pin_swclk    GPIO number for SWCLK
 * @param[in] pin_swdio    GPIO number for SWDIO
 */
static inline void pio_swd_init(const rp_pio_sm_t *smp, uint32_t prog_offset,
                                 uint32_t pin_swclk, uint32_t pin_swdio) {
  /* Disable state machine for (re)configuration. */
  pioSmDisableX(smp);

  /* PINCTRL: side-set on SWCLK, OUT/IN/SET on SWDIO. */
  uint32_t pinctrl =
    (pin_swdio << PIO_SM_PINCTRL_OUT_BASE_Pos) |
    (pin_swdio << PIO_SM_PINCTRL_SET_BASE_Pos) |
    (pin_swclk << PIO_SM_PINCTRL_SIDESET_BASE_Pos) |
    (pin_swdio << PIO_SM_PINCTRL_IN_BASE_Pos) |
    (1U << PIO_SM_PINCTRL_OUT_COUNT_Pos) |   /* 1 OUT pin (SWDIO) */
    (1U << PIO_SM_PINCTRL_SET_COUNT_Pos) |   /* 1 SET pin (SWDIO) */
    (2U << PIO_SM_PINCTRL_SIDESET_COUNT_Pos); /* 2 side-set bits (1 pin + enable) */
  pioSmSetPinctrlX(smp, pinctrl);

  /* EXECCTRL: wrap range, side-set enable bit. */
  pioSmSetExecctrlX(smp,
    PIO_SM_EXECCTRL_WRAP(prog_offset + PIO_SWD_WRAP_TARGET,
                          prog_offset + PIO_SWD_WRAP) |
    PIO_SM_EXECCTRL_SIDE_EN);

  /* SHIFTCTRL: shift right (LSB first), no auto push/pull. */
  pioSmSetShiftctrlX(smp,
    PIO_SM_SHIFTCTRL_IN_SHIFTDIR |
    PIO_SM_SHIFTCTRL_OUT_SHIFTDIR);

  /* Force-set pin directions and initial values.
   * Side-set controls SWCLK value but NOT output enable.
   * Must use set pindirs to enable output on both pins. */

  /* SWCLK: output enabled, initial value high. */
  pioSmSetPinctrlX(smp,
    (1U << PIO_SM_PINCTRL_SET_COUNT_Pos) |
    (pin_swclk << PIO_SM_PINCTRL_SET_BASE_Pos));
  pioSmExecX(smp, 0xE081U);  /* set pindirs, 1 */
  pioSmExecX(smp, 0xE001U);  /* set pins, 1 */

  /* SWDIO: output enabled, initial value high. */
  pioSmSetPinctrlX(smp,
    (1U << PIO_SM_PINCTRL_SET_COUNT_Pos) |
    (pin_swdio << PIO_SM_PINCTRL_SET_BASE_Pos));
  pioSmExecX(smp, 0xE081U);  /* set pindirs, 1 */
  pioSmExecX(smp, 0xE001U);  /* set pins, 1 */

  /* Restore PINCTRL. */
  pioSmSetPinctrlX(smp, pinctrl);

  /* Set initial PC to get_next_cmd (command dispatch). */
  pioSmSetPCX(smp, prog_offset + PIO_SWD_OFFSET_GET_NEXT_CMD);

  /* Clear FIFOs. */
  pioSmClearFifosX(smp);

  /* Enable state machine. */
  pioSmEnableX(smp);
}

/**
 * @brief   Set PIO SM clock divider.
 *
 * @param[in] smp      allocated state machine descriptor
 * @param[in] clk_div  clock divider as 16.8 fixed-point (integer << 8 | frac)
 */
static inline void pio_swd_set_clkdiv(const rp_pio_sm_t *smp,
                                        uint32_t clk_div) {
  /* CLKDIV register: [31:16]=integer, [15:8]=fractional, [7:0]=reserved. */
  uint32_t int_part = clk_div >> 8;
  uint32_t frac_part = clk_div & 0xFFU;
  pioSmSetClkdivX(smp, PIO_SM_CLKDIV(int_part, frac_part));
}

#endif /* PIO_SWD_H */
