/*
 * Copyright (C) 2026 Eric Molitor <github.com/emolitor>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PIO-based SWD driver for RP2040/RP2350.
 *
 * PIO program and inline helpers for loading, configuring, and driving
 * SWD via a PIO state machine. PIO assembly source is in probe_swd.pio;
 * the instruction array is generated by pioasm into probe_swd.pio.h.
 *
 * The PIO program implements a command-dispatch architecture:
 *   - Command word: bits[7:0]=count-1, bit[8]=direction, bits[13:9]=PC
 *   - Side-set: 1-bit optional on SWCLK (4 PIO cycles per SWCLK edge)
 *   - Writes are fire-and-forget (TX FIFO only)
 *   - Reads block on RX FIFO
 */

#ifndef PIO_SWD_H
#define PIO_SWD_H

#include "hal.h"

/*===========================================================================*/
/* PIO program: generated by pioasm from probe_swd.pio.                      */
/*===========================================================================*/

/* Skip Pico SDK struct/helpers — we only need the instruction array. */
#define PICO_NO_HARDWARE 1
#include "probe_swd.pio.h"
#undef PICO_NO_HARDWARE

/* Map generated names to local constants. */
#define PIO_SWD_OFFSET_WRITE_CMD      probe_swd_offset_write_cmd
#define PIO_SWD_OFFSET_TURNAROUND_CMD probe_swd_offset_turnaround_cmd
#define PIO_SWD_OFFSET_GET_NEXT_CMD   probe_swd_offset_get_next_cmd
#define PIO_SWD_OFFSET_READ_CMD       probe_swd_offset_read_cmd
#define PIO_SWD_WRAP_TARGET           probe_swd_wrap_target
#define PIO_SWD_WRAP                  probe_swd_wrap
#define PIO_SWD_PROGRAM_LEN           (sizeof(probe_swd_program_instructions) / sizeof(uint16_t))

/*===========================================================================*/
/* Command word construction.                                                */
/*===========================================================================*/

/* Command types — resolved to PIO instruction addresses. */
#define PIO_SWD_CMD_WRITE       PIO_SWD_OFFSET_WRITE_CMD
#define PIO_SWD_CMD_READ        PIO_SWD_OFFSET_READ_CMD
#define PIO_SWD_CMD_TURNAROUND  PIO_SWD_OFFSET_TURNAROUND_CMD
#define PIO_SWD_CMD_SKIP        PIO_SWD_OFFSET_GET_NEXT_CMD

/**
 * @brief   Build a PIO SWD command word.
 *
 * @param[in] bit_count   number of bits (1..256)
 * @param[in] out_en      true=output, false=input
 * @param[in] cmd_offset  command label offset within program
 * @param[in] prog_offset base address of program in PIO instruction memory
 * @return    32-bit command word for TX FIFO
 */
static inline uint32_t pio_swd_cmd(uint32_t bit_count, bool out_en,
                                    uint32_t cmd_offset,
                                    uint32_t prog_offset) {
  uint32_t addr = prog_offset + cmd_offset;
  return ((bit_count - 1U) & 0xFFU) |
         ((uint32_t)out_en << 8) |
         (addr << 9);
}

/*===========================================================================*/
/* PIO FIFO access helpers.                                                  */
/*===========================================================================*/

/**
 * @brief   Write a word to the PIO TX FIFO (blocking).
 */
static inline void pio_swd_put(PIO_TypeDef *pio, uint32_t sm, uint32_t data) {
  while (pio->FSTAT & (1U << (16U + sm)))
    ;  /* Wait while TX FIFO full. */
  pio->TXF[sm] = data;
}

/**
 * @brief   Read a word from the PIO RX FIFO (blocking).
 */
static inline uint32_t pio_swd_get(PIO_TypeDef *pio, uint32_t sm) {
  while (pio->FSTAT & (1U << (8U + sm)))
    ;  /* Wait while RX FIFO empty. */
  return pio->RXF[sm];
}

/**
 * @brief   Drain RX FIFO (discard stale data).
 */
static inline void pio_swd_drain(PIO_TypeDef *pio, uint32_t sm) {
  while (!(pio->FSTAT & (1U << (8U + sm))))
    (void)pio->RXF[sm];
}

/**
 * @brief   Wait for SM to become idle (TX stall).
 * @note    FDEBUG bit 24+sm is the TX stall sticky flag.
 */
static inline void pio_swd_wait_idle(PIO_TypeDef *pio, uint32_t sm) {
  uint32_t mask = 1U << (24U + sm);
  pio->FDEBUG = mask;  /* Clear sticky flag. */
  while (!(pio->FDEBUG & mask))
    ;  /* Wait for stall (SM waiting on pull). */
}

/*===========================================================================*/
/* PIO state machine configuration.                                          */
/*===========================================================================*/

/* FSTAT bit positions. */
#define PIO_FSTAT_TXFULL_BIT(sm)     (1U << (16U + (sm)))
#define PIO_FSTAT_RXEMPTY_BIT(sm)    (1U << (8U + (sm)))

/* PINCTRL field positions. */
#define PIO_PINCTRL_OUT_BASE_POS     0U
#define PIO_PINCTRL_SET_BASE_POS     5U
#define PIO_PINCTRL_SIDESET_BASE_POS 10U
#define PIO_PINCTRL_IN_BASE_POS      15U
#define PIO_PINCTRL_OUT_COUNT_POS    20U
#define PIO_PINCTRL_SET_COUNT_POS    26U
#define PIO_PINCTRL_SIDESET_COUNT_POS 29U

/* EXECCTRL field positions. */
#define PIO_EXECCTRL_WRAP_BOTTOM_POS 7U
#define PIO_EXECCTRL_WRAP_TOP_POS    12U
#define PIO_EXECCTRL_SIDE_EN_POS     30U
#define PIO_EXECCTRL_SIDE_PINDIR_POS 29U

/* SHIFTCTRL field positions. */
#define PIO_SHIFTCTRL_AUTOPUSH_POS   16U
#define PIO_SHIFTCTRL_AUTOPULL_POS   17U
#define PIO_SHIFTCTRL_IN_SHIFTDIR_POS  18U
#define PIO_SHIFTCTRL_OUT_SHIFTDIR_POS 19U
#define PIO_SHIFTCTRL_PUSH_THRESH_POS  20U
#define PIO_SHIFTCTRL_PULL_THRESH_POS  25U

/* CLKDIV field positions. */
#define PIO_CLKDIV_FRAC_POS         8U
#define PIO_CLKDIV_INT_POS          16U

/**
 * @brief   Load PIO program and configure state machine for SWD.
 *
 * @param[in] pio         PIO peripheral (PIO0 or PIO1)
 * @param[in] sm          state machine index (0-3)
 * @param[in] pin_swclk   GPIO number for SWCLK
 * @param[in] pin_swdio   GPIO number for SWDIO
 * @return    program offset in instruction memory
 */
static inline uint32_t pio_swd_init(PIO_TypeDef *pio, uint32_t sm,
                                     uint32_t pin_swclk, uint32_t pin_swdio) {
  uint32_t prog_offset = 0U;
  uint32_t i;

  /* Disable state machine. */
  pio->CTRL &= ~(1U << sm);

  /* Load program at offset 0. */
  for (i = 0U; i < PIO_SWD_PROGRAM_LEN; i++)
    pio->INSTR_MEM[prog_offset + i] = probe_swd_program_instructions[i];

  /* PINCTRL: side-set on SWCLK, OUT/IN/SET on SWDIO. */
  pio->SM[sm].PINCTRL =
    (pin_swdio << PIO_PINCTRL_OUT_BASE_POS) |
    (pin_swdio << PIO_PINCTRL_SET_BASE_POS) |
    (pin_swclk << PIO_PINCTRL_SIDESET_BASE_POS) |
    (pin_swdio << PIO_PINCTRL_IN_BASE_POS) |
    (1U << PIO_PINCTRL_OUT_COUNT_POS) |   /* 1 OUT pin (SWDIO) */
    (1U << PIO_PINCTRL_SET_COUNT_POS) |   /* 1 SET pin (SWDIO) */
    (2U << PIO_PINCTRL_SIDESET_COUNT_POS); /* 2 side-set bits (1 pin + enable) */

  /* EXECCTRL: wrap range, side-set enable bit. */
  pio->SM[sm].EXECCTRL =
    ((prog_offset + PIO_SWD_WRAP_TARGET) << PIO_EXECCTRL_WRAP_BOTTOM_POS) |
    ((prog_offset + PIO_SWD_WRAP) << PIO_EXECCTRL_WRAP_TOP_POS) |
    (1U << PIO_EXECCTRL_SIDE_EN_POS);     /* Optional side-set */

  /* SHIFTCTRL: shift right (LSB first), no auto push/pull. */
  pio->SM[sm].SHIFTCTRL =
    (1U << PIO_SHIFTCTRL_IN_SHIFTDIR_POS) |  /* Shift right */
    (1U << PIO_SHIFTCTRL_OUT_SHIFTDIR_POS);   /* Shift right */

  /* Force-set pin directions and initial values.
   * Side-set controls SWCLK value but NOT output enable.
   * Must use set pindirs to enable output on both pins. */
  uint32_t pinctrl_saved = pio->SM[sm].PINCTRL;

  /* SWCLK: output enabled, initial value high. */
  pio->SM[sm].PINCTRL = (1U << PIO_PINCTRL_SET_COUNT_POS) |
                          (pin_swclk << PIO_PINCTRL_SET_BASE_POS);
  pio->SM[sm].INSTR = 0xE081U;  /* set pindirs, 1 */
  pio->SM[sm].INSTR = 0xE001U;  /* set pins, 1 */

  /* SWDIO: output enabled, initial value high. */
  pio->SM[sm].PINCTRL = (1U << PIO_PINCTRL_SET_COUNT_POS) |
                          (pin_swdio << PIO_PINCTRL_SET_BASE_POS);
  pio->SM[sm].INSTR = 0xE081U;  /* set pindirs, 1 */
  pio->SM[sm].INSTR = 0xE001U;  /* set pins, 1 */

  /* Restore PINCTRL. */
  pio->SM[sm].PINCTRL = pinctrl_saved;

  /* Set initial PC to get_next_cmd (command dispatch). */
  pio->SM[sm].INSTR = 0x0000U | (prog_offset + PIO_SWD_OFFSET_GET_NEXT_CMD);

  /* Drain FIFOs. */
  pio_swd_drain(pio, sm);

  /* Enable state machine. */
  pio->CTRL |= (1U << sm);

  return prog_offset;
}

/**
 * @brief   Disable PIO state machine.
 */
static inline void pio_swd_deinit(PIO_TypeDef *pio, uint32_t sm) {
  pio->CTRL &= ~(1U << sm);
}

/**
 * @brief   Set PIO SM clock divider.
 *
 * @param[in] pio      PIO peripheral
 * @param[in] sm       state machine index
 * @param[in] clk_div  clock divider as 16.8 fixed-point (integer << 8 | frac)
 */
static inline void pio_swd_set_clkdiv(PIO_TypeDef *pio, uint32_t sm,
                                        uint32_t clk_div) {
  /* CLKDIV register: [31:16]=integer, [15:8]=fractional, [7:0]=reserved. */
  uint32_t int_part = clk_div >> 8;
  uint32_t frac_part = clk_div & 0xFFU;
  pio->SM[sm].CLKDIV = (int_part << PIO_CLKDIV_INT_POS) |
                        (frac_part << PIO_CLKDIV_FRAC_POS);
}

#endif /* PIO_SWD_H */
