/*
 * Copyright (C) 2026 Eric Molitor <github.com/emolitor>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <https://www.gnu.org/licenses/>.
 */

/*
 * PIO-based SWD driver for RP2040/RP2350.
 *
 * PIO program and inline helpers for configuring and driving SWD via a
 * PIO state machine.  Uses the ChibiOS PIO LLD (PIOv1) for state machine
 * allocation, program loading, and register access.
 *
 * PIO assembly source is in probe_swd.pio; the instruction array is
 * generated by pioasm into probe_swd.pio.h.
 *
 * The PIO program implements a command-dispatch architecture:
 *   - Command word: bits[7:0]=count-1, bit[8]=direction, bits[13:9]=PC
 *   - Side-set: 1-bit optional on SWCLK (4 PIO cycles per SWCLK edge)
 *   - Writes are fire-and-forget (TX FIFO only)
 *   - Reads block on RX FIFO
 */

#ifndef PIO_SWD_H
#define PIO_SWD_H

#include "hal.h"
#include "rp_pio.h"

/*===========================================================================*/
/* PIO program: generated by pioasm from probe_swd.pio.                      */
/*===========================================================================*/

/* Skip Pico SDK struct/helpers — we only need the instruction array. */
#define PICO_NO_HARDWARE 1
#include "probe_swd.pio.h"
#undef PICO_NO_HARDWARE

/* Map generated names to local constants. */
#define PIO_SWD_OFFSET_WRITE_CMD      probe_swd_offset_write_cmd
#define PIO_SWD_OFFSET_TURNAROUND_CMD probe_swd_offset_turnaround_cmd
#define PIO_SWD_OFFSET_GET_NEXT_CMD   probe_swd_offset_get_next_cmd
#define PIO_SWD_OFFSET_READ_CMD       probe_swd_offset_read_cmd
#define PIO_SWD_OFFSET_BARRIER_CMD    probe_swd_offset_barrier_cmd
#define PIO_SWD_WRAP_TARGET           probe_swd_wrap_target
#define PIO_SWD_WRAP                  probe_swd_wrap
#define PIO_SWD_PROGRAM_LEN           (sizeof(probe_swd_program_instructions) / sizeof(uint16_t))

/*===========================================================================*/
/* PIO program descriptor for LLD.                                           */
/*===========================================================================*/

static const rp_pio_program_t pio_swd_program = {
  .instructions = probe_swd_program_instructions,
  .length       = sizeof(probe_swd_program_instructions) / sizeof(uint16_t),
  .origin       = 0   /* Load at offset 0. */
};

/*===========================================================================*/
/* Command word construction.                                                */
/*===========================================================================*/

/* Command types — resolved to PIO instruction addresses. */
#define PIO_SWD_CMD_WRITE       PIO_SWD_OFFSET_WRITE_CMD
#define PIO_SWD_CMD_READ        PIO_SWD_OFFSET_READ_CMD
#define PIO_SWD_CMD_TURNAROUND  PIO_SWD_OFFSET_TURNAROUND_CMD
#define PIO_SWD_CMD_SKIP        PIO_SWD_OFFSET_GET_NEXT_CMD

/**
 * @brief   Build a PIO SWD command word.
 *
 * @param[in] bit_count   number of bits (1..256)
 * @param[in] out_en      true=output, false=input
 * @param[in] cmd_offset  command label offset within program
 * @param[in] prog_offset base address of program in PIO instruction memory
 * @return    32-bit command word for TX FIFO
 */
static inline uint32_t pio_swd_cmd(uint32_t bit_count, bool out_en,
                                    uint32_t cmd_offset,
                                    uint32_t prog_offset) {
  uint32_t addr = prog_offset + cmd_offset;
  return ((bit_count - 1U) & 0xFFU) |
         ((uint32_t)out_en << 8) |
         (addr << 9);
}

/*===========================================================================*/
/* PIO state machine configuration.                                          */
/*===========================================================================*/

/**
 * @brief   Encode a 16.8 fixed-point divider as a CLKDIV register value.
 * @details CLKDIV is [31:16]=integer, [15:8]=fractional, [7:0]=reserved.
 *          The maximum divider 65536.0 does not fit the 16-bit integer
 *          field and is encoded as integer zero, which is also the only
 *          integer value the LLD accepts with a zero fraction. Anything at
 *          or above it is clamped there: encoding such a value directly
 *          would shift the integer part out of the 32-bit register and
 *          could select a smaller divider (a faster clock) instead of the
 *          intended maximum.
 *
 * @param[in] clk_div  clock divider as 16.8 fixed-point
 * @return    CLKDIV register value
 */
static inline uint32_t pio_swd_clkdiv_reg(uint32_t clk_div) {
  if (clk_div >= 0x1000000U)
    return PIO_SM_CLKDIV(0U, 0U);
  return PIO_SM_CLKDIV(clk_div >> 8, clk_div & 0xFFU);
}

/**
 * @brief   Configure state machine for SWD operation.
 * @pre     SM must be allocated via pioSmAlloc() and program loaded via
 *          pioProgramLoad().
 *
 * @param[in] smp          allocated state machine descriptor
 * @param[in] prog_offset  program offset from pioProgramLoad()
 * @param[in] pin_swclk    GPIO number for SWCLK
 * @param[in] pin_swdio    GPIO number for SWDIO
 */
static inline void pio_swd_init(const rp_pio_sm_t *smp, uint32_t prog_offset,
                                 uint32_t pin_swclk, uint32_t pin_swdio,
                                 uint32_t clk_div) {
  rp_pio_sm_config_t cfg;
  uint32_t rel_swclk = pioGpioToRel(smp->block, pin_swclk);
  uint32_t rel_swdio = pioGpioToRel(smp->block, pin_swdio);
  uint32_t clkdiv_reg = pio_swd_clkdiv_reg(clk_div);

  /*
   * Use the current PIO LLD's complete initialization path. In addition to
   * applying the register images this clears debug/FIFO state and restarts
   * the state machine and divider, which is required when reconnecting
   * after a previous program has been unloaded.
   */
  pioSmConfigDefaultX(&cfg);
  pioSmConfigSetWrapX(&cfg,
                      prog_offset + PIO_SWD_WRAP_TARGET,
                      prog_offset + PIO_SWD_WRAP);
  pioSmConfigSetSidesetX(&cfg, 2U, true, false);
  pioSmConfigSetSidesetPinsX(&cfg, rel_swclk);
  pioSmConfigSetOutPinsX(&cfg, rel_swdio, 1U);
  pioSmConfigSetSetPinsX(&cfg, rel_swdio, 1U);
  pioSmConfigSetInPinsX(&cfg, rel_swdio);
  pioSmConfigSetClkdivX(&cfg,
                        clkdiv_reg >> PIO_SM_CLKDIV_INT_Pos,
                        (clkdiv_reg & PIO_SM_CLKDIV_FRAC_Msk) >>
                          PIO_SM_CLKDIV_FRAC_Pos);
  pioSmInit(smp, prog_offset + PIO_SWD_OFFSET_GET_NEXT_CMD, &cfg);

  /* Route pads after the SM has been initialized, then enable both outputs. */
  pioGpioInitPadX(smp, pin_swclk,
                  RP_PIO_PAD_DEFAULT | RP_PIO_PAD_SLEWFAST);
  pioGpioInitPadX(smp, pin_swdio,
                  RP_PIO_PAD_DEFAULT | RP_PIO_PAD_PUE |
                  RP_PIO_PAD_SLEWFAST);
  pioSmSetConsecutivePindirsX(smp, pin_swclk, 2U, true);

  /* Enable state machine. */
  pioSmEnableX(smp);
}

/**
 * @brief   Set PIO SM clock divider.
 *
 * @param[in] smp      allocated state machine descriptor
 * @param[in] clk_div  clock divider as 16.8 fixed-point (integer << 8 | frac)
 */
static inline void pio_swd_set_clkdiv(const rp_pio_sm_t *smp,
                                        uint32_t clk_div) {
  pioSmSetClkdivX(smp, pio_swd_clkdiv_reg(clk_div));
}

#endif /* PIO_SWD_H */
