// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// probe_swd //
// --------- //

#define probe_swd_wrap_target 3
#define probe_swd_wrap 10
#define probe_swd_pio_version 0

#define probe_swd_offset_write_cmd 0u
#define probe_swd_offset_turnaround_cmd 0u
#define probe_swd_offset_get_next_cmd 3u
#define probe_swd_offset_read_cmd 8u

static const uint16_t probe_swd_program_instructions[] = {
    0x80a0, //  0: pull   block
    0x7101, //  1: out    pins, 1         side 0 [1]
    0x1941, //  2: jmp    x--, 1          side 1 [1]
            //     .wrap_target
    0x90a0, //  3: pull   block           side 0
    0x6028, //  4: out    x, 8
    0x6081, //  5: out    pindirs, 1
    0x60a5, //  6: out    pc, 5
    0xa042, //  7: nop
    0x5901, //  8: in     pins, 1         side 1 [1]
    0x1047, //  9: jmp    x--, 7          side 0
    0x8020, // 10: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program probe_swd_program = {
    .instructions = probe_swd_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = probe_swd_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config probe_swd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + probe_swd_wrap_target, offset + probe_swd_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

